version: '3'

services:
    app:
      build:
        context: ./nodejs
        dockerfile: Dockerfile
      container_name: nodejs
      working_dir: /app
      volumes: 
        - ./nodejs:/app
      networks:
        - nodeginx
      tty: true
      entrypoint:  dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm start"


    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      environment:
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=nodedb
      networks:
        - nodeginx
    
    nginx:
        build:
          context: ./nginx
          dockerfile: Dockerfile.prod
        container_name: nginx
        networks:
          - nodeginx
        ports:
          -   "8080:80"

networks: 
    nodeginx:
        driver: bridge

  
